image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules
  script:
  - apt-get update -qq && apt-get install -y -qq rsync
  - git submodule update --init
  - npm install
  - npm run build
  artifacts:
    paths:
    - public
  only:
  - master
